{% set name = "scyjava" %}
{% set version = "1.10.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f86e8637e8e79de56d643d978e83253ff38974a43d76579f3792d5e076d5681

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - jpype1 >=1.3.0
    - jgo
  run:
    - python >=3.7
    - jpype1 >=1.3.0
    - jgo
    - maven
    - openjdk

test:
  imports:
    - scyjava
    - scyjava.config

about:
  home: https://github.com/scijava/scyjava
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Supercharged Java access from Python.
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
