{% set name = "scyjava" %}
{% set version = "1.4.1" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: affa4006bb56d6f6ea30df30f9b87c0d596be953e79555e4a17a91eae03d1006

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - jpype1 >=1.3.0
    - jgo
  run:
    - python >=3.6
    - jpype1 >=1.3.0
    - jgo
    - maven
    - openjdk

test:
  imports:
    - scyjava
    - scyjava.config

about:
  home: https://github.com/scijava/scyjava
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Supercharged Java access from Python.
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
