{% set name = "scyjava" %}
{% set version = "0.2.2" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a947c14548bdb57e4eb6f15b4307022719adfd35d9468dd143c83efda0a556e9

build:
  number: {{ build_number }}
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps"
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
    - pyjnius
    - jgo
  run:
    - python
    - pyjnius
    - jgo
    - maven
    - openjdk

test:
  imports:
    - scyjava
    - scyjava_config

about:
  home: https://github.com/scijava/scyjava
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  summary: 'Supercharged Java access from Python.'
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - hanslovsky
    - hadim
