{% set name = "scyjava" %}
{% set version = "1.12.1" %}
{% set build_number = 0 %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e91c9faf295b2f62ce53f8d882a9abcc02ef3d3cfaafb0c2b2a2b6a5449cb21

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jpype1 >=1.3.0
    - jgo
    - setuptools >=77.0.0
  run:
    - python >={{ python_min }}
    - jpype1 >=1.3.0
    - jgo
    - cjdk

test:
  requires:
    - python {{ python_min }}
  imports:
    - scyjava

about:
  home: https://github.com/scijava/scyjava
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Supercharged Java access from Python.
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
