{% set name = "scyjava" %}
{% set version = "1.10.2" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 483eda5017127ffa3907390cea2868fe86e18d36c21b16c30e21eb1147b5bc4c

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jpype1 >=1.3.0
    - jgo
    - setuptools >=61.2
  run:
    - python >=3.8
    - jpype1 >=1.3.0
    - jgo
    - maven !=3.9.7
    - openjdk

test:
  requires:
    - python {{ python_min }}
  imports:
    - scyjava
    - scyjava.config

about:
  home: https://github.com/scijava/scyjava
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Supercharged Java access from Python.
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
