{% set name = "scyjava" %}
{% set version = "1.3.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e99156e2eb5b4c27d2dccba879dbcb4557edec79f477c4bb1f85aba101e096e

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - jpype1
    - jgo
  run:
    - python >=3.6
    - jpype1
    - jgo
    - maven
    - openjdk

test:
  imports:
    - scyjava
    - scyjava.config

about:
  home: https://github.com/scijava/scyjava
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Supercharged Java access from Python.
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
