{% set name = "scyjava" %}
{% set version = "1.5.1" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c1b93d5d3b8b2d2fdbad3e2a21d50102e6ad97e4d2de83dec9c117a25269861

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - jpype1 >=1.3.0
    - jgo
  run:
    - python >=3.6
    - jpype1 >=1.3.0
    - jgo
    - maven
    - openjdk

test:
  imports:
    - scyjava
    - scyjava.config

about:
  home: https://github.com/scijava/scyjava
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Supercharged Java access from Python.
  doc_url: https://github.com/scijava/scyjava
  dev_url: https://github.com/scijava/scyjava

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
