travis:
  secure:
    BINSTAR_TOKEN: arUwyHNGakuDFFEZ/QOfT+FNJZ5r/PRSTNAd8YVzwW3trisf3K4mmuar3yVk+szZ/RIWWdkvyOmYg59ZK2TFQVznr8k1aO6BeJPJY+nXInQ0dhkWZhHAj+rMDAUUFP2Hr6mBksJpf+j0jQJ5nbALl1JOsEBcsVZSvdBLqO+WciZ8DfvUM27+ZD1kqx6jn1KxWpzOeTjFZaJkDZkLNc3r7tQLoJNxNyZG1tDU+Hd1mea910/pBh1/C2AqnGlHsulXwCsqcWOyqu189/c3L6XNzS7/sc0+9WdOp6fsM9Xuj07HZehiGhd4ZcONUaYa3XhIhViq0gP5IurCTvk0cCRuFon+54zw0Ys5151GmCkaQBJKOicD9jiv4N2GMQpT61+d6CPcFjvetXZuIC4nXeykOqMATMyDB4BJ5JJETS4TDxl5sXeNPlPUxjahpKdqY6QLLtv+/F6wynWZj2WDwP+kdhqSuto0bmae7hzTut74ZyZF0XrmiFawe3Vi/4D396a3NCFKKXjajXDZTa/vlmB09shErO1D0L2SHT62NSgiFksBdjCYKj+vCYWy+bJPaKotDD9z6uwo1q7vpR13E4Tn8rmpPf/6FIxlkjFWvxGR+Tt0baUWl+tfX7POVZyPg2NH4lOk3dUJWTA5HpozhTXqB5VjmxS1JJh3EP2U/Dtj6Jc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
